### ISSUE TITLE
Need better story for API management for communities 

### ISSUE THREAD

**Issue by ceseale** [polyswarm/api-key-management#7]
**Is your feature request related to a problem? Please describe.**
We need to be able to manage the revoking and creation of api keys for different communities.

**Describe alternatives you've considered**
We talked about adding a new table that tracks the communities each API key has access.

**Comment by mjkoo** [comment]
This is partially addressed by #11 but is not yet fully baked in my opinion, in terms of managing access to communities private vs public etc. so leaving open

**Comment by mjkoo** [comment]
This has been resolved by checking community membership in polyswarmd closing
